env:
  browser: true
  es6: true
extends: 'eslint:recommended'
globals:
  browser: false
rules:
  max-len:
    - error
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
parserOptions:
  ecmaVersion: 2017
